<?php

namespace AlbaranesBundle\Repository;

/**
 * ConceptosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConceptosRepository extends \Doctrine\ORM\EntityRepository
{
    /* 
    * Obtiene el importe total de un albaran
    */
    public function dameImporteTotalAlbaran($albaran){
            // Listado completo de clientes con todas direcciones

            $consulta = $this->getQueryBuilder();
            $consulta ->select('sum(c.cantidad* c.precio) as Total')
                    ->leftJoin('c.albaran', 'a')
                    ->Where("a.id =:id")
                    ->setParameter('id', $albaran)
                    ->groupby('a.id')
            ->getQuery();
            $Total =$consulta->getQuery()->getResult();
            // Devuelve el importe total de los conceptos del albaran.
            return $Total[0]['Total'];
    }
    
    
    private function getQueryBuilder()
    {
        $em = $this->getEntityManager();
        $qb = $em->getRepository('AlbaranesBundle:Conceptos')
            ->createQueryBuilder('c');
        return $qb;
    }
}
