producto_index:
    path:     /
    defaults: { _controller: "ProductosBundle:Producto:index" }
    methods:  GET

producto_show:
    path:     /{id}/show
    defaults: { _controller: "ProductosBundle:Producto:show" }
    methods:  GET

producto_new:
    path:     /nuevo/{cliente}
    defaults: { _controller: "ProductosBundle:Producto:new" }
    methods:  [GET, POST]

producto_edit:
    path:     /{id}/{cliente}/modificar
    defaults: { _controller: "ProductosBundle:Producto:edit" }
    methods:  [GET, POST]

producto_delete:
    path:     /{id}/delete
    defaults: { _controller: "ProductosBundle:Producto:delete" }
    methods:  DELETE

listado_familias:
    path:     /listadofamilias
    defaults: { _controller: "ProductosBundle:Familia:index" }
    methods:  GET
    

familia_new:
    path:     /new
    defaults: { _controller: "ProductosBundle:Familia:new" }
    methods:  [GET, POST]

familia_edit:
    path:     /{id}/edit
    defaults: { _controller: "ProductosBundle:Familia:edit" }
    methods:  [GET, POST]

familia_delete:
    path:     /{id}/delete
    defaults: { _controller: "ProductosBundle:Familia:delete" }
    methods:  DELETE
