incidencia_index:
    path:     /
    defaults: { _controller: "IncidenciasBundle:Incidencia:index" }
    methods:  GET

incidencia_show:
    path:     /{id}/show
    defaults: { _controller: "IncidenciasBundle:Incidencia:show" }
    methods:  GET

incidencia_nueva:
    path:     /nueva/{cliente}/{direccion}/{producto}
    defaults: { _controller: "IncidenciasBundle:Incidencia:new" }
    methods:  [GET, POST]

incidencia_edit:
    path:     /{id}/edit
    defaults: { _controller: "IncidenciasBundle:Incidencia:edit" }
    methods:  [GET, POST]

incidencia_delete:
    path:     /{id}/delete
    defaults: { _controller: "IncidenciasBundle:Incidencia:delete" }
    methods:  DELETE
