<?php

namespace TrabajadoresBundle\Repository;

/**
 * TrabajadoresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrabajadoresRepository extends \Doctrine\ORM\EntityRepository
{
    
    /* 
    * Obtiene el listado de los trabajadores de una empresa
    */
    public function dameTrabajadoresEmpresa($empresa){
            // Listado completo de trabajadores

            $consulta = $this->getQueryBuilder();
            
            $consulta->Where("t.baja IS NULL") ;
            $consulta->andWhere("t.empresa =:empresa")
                    ->setParameter('empresa', $empresa);
            $consulta->orderby('t.nombre', 'ASC')
            ->getQuery();

            return $consulta->getQuery()->getResult();
    }

    /* 
    * Obtiene el listado de los trabajadores de una empresa
    */
    public function dameListaTrabajadoresArray($empresa){
            // Listado completo de trabajadores
            $datos = []; $i=0;
            $consulta = $this->getQueryBuilder();
            
            $consulta->Where("t.baja IS NULL") ;
            $consulta->andWhere("t.empresa =:empresa")
                    ->setParameter('empresa', $empresa);
            $consulta->orderby('t.nombre', 'ASC')
            ->getQuery();
             $consulta->getQuery()->getResult();
            $lista = $consulta->getQuery()->iterate();
            foreach ($lista as $item){
                $datos[$i]['id'] = $item[0]->getId();
                $i++;
            }
            return $datos;
    }
    
    /* 
    * Obtiene el listado de los clientes de una empresa
    * según un criterio de búsqueda
    */
    public function buscaTrabajadoresSegunTexto($cadena,$empresa){
            // Listado completo de clientes

        
            $consulta = $this->getQueryBuilder();
            $consulta->Where("t.baja IS NULL") 
                    ->andWhere("t.empresa =:empresa")
                    ->andWhere("t.nombre LIKE :nombre")
                    ->setParameter('empresa', $empresa)
                    ->setParameter('nombre', '%'.$cadena.'%');

            $consulta->getQuery();

            return $consulta->getQuery()->getResult();
    }   
    
    private function getQueryBuilder()
    {
        $em = $this->getEntityManager();

        $qb = $em->getRepository('TrabajadoresBundle:Trabajadores')
            ->createQueryBuilder('t');

        return $qb;
    }
}
