<?php

namespace ProductosBundle\Repository;

/**
 * AccionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccionesRepository extends \Doctrine\ORM\EntityRepository
{
}
