<?php

namespace ProductosBundle\Repository;

/**
 * FamiliaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamiliaRepository extends \Doctrine\ORM\EntityRepository
{
}
