<?php

namespace ProductosBundle\Repository;

/**
 * TipoContratoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoContratoRepository extends \Doctrine\ORM\EntityRepository
{
}
