partes_listado:
    path:     /
    defaults: { _controller: "PartesBundle:Partes:index" }
    methods:  GET

partes_show:
    path:     /{id}/muestraParte
    defaults: { _controller: "PartesBundle:Partes:show" }
    methods:  GET

partes_nuevo:
    path:     /nuevo/{id}/{tipo}/{fecha}
    defaults: { _controller: "PartesBundle:Partes:new" }
    methods:  [GET, POST]

partes_edit:
    path:     /{id}/editar
    defaults: { _controller: "PartesBundle:Partes:edit" }
    methods:  [GET, POST]

partes_delete:
    path:     /{id}/delete
    defaults: { _controller: "PartesBundle:Partes:delete" }
    methods:  DELETE
    
partes_diario:
    path:     /{fecha}/muestraPartes
    defaults: { _controller: "PartesBundle:Partes:diarioPartes" }
    methods:  GET
#
#partes_busca:
#    path:     /buscaParte
#    defaults: { _controller: "PartesBundle:Partes:buscaParteNombre" }
#    methods:  [POST]