partes_index:
    path:     /
    defaults: { _controller: "PartesBundle:Partes:index" }
    methods:  GET

partes_show:
    path:     /{id}/show
    defaults: { _controller: "PartesBundle:Partes:show" }
    methods:  GET

partes_new:
    path:     /new
    defaults: { _controller: "PartesBundle:Partes:new" }
    methods:  [GET, POST]

partes_edit:
    path:     /{id}/edit
    defaults: { _controller: "PartesBundle:Partes:edit" }
    methods:  [GET, POST]

partes_delete:
    path:     /{id}/delete
    defaults: { _controller: "PartesBundle:Partes:delete" }
    methods:  DELETE
