partes_listado:
    path:     /
    defaults: { _controller: "PartesBundle:Partes:index" }
    methods:  GET

partes_show:
    path:     /{id}/muestraParte
    defaults: { _controller: "PartesBundle:Partes:show" }
    methods:  GET

partes_ruta:
    path:     /{fecha}/ruta/{tecnico}
    defaults: { _controller: "PartesBundle:Partes:rutaPDF" }
    methods:  GET

partes_nuevo_mantenimiento:
    path:     /nuevo/{id}/{fecha}
    defaults: { _controller: "PartesBundle:Partes:nuevoMantenimiento" }
    methods:  [GET, POST]


partes_nueva_incidencia:
    path:     /nuevo/{id}
    defaults: { _controller: "PartesBundle:Partes:nuevaIncidencia" }
    methods:  [GET, POST]

partes_edit:
    path:     /{id}/editar
    defaults: { _controller: "PartesBundle:Partes:edit" }
    methods:  [GET, POST]

partes_delete:
    path:     /{id}/delete
    defaults: { _controller: "PartesBundle:Partes:delete" }
    methods:  DELETE
    
partes_diario:
    path:     /{fecha}/muestraPartes
    defaults: { _controller: "PartesBundle:Partes:diarioPartes" }
    methods:  GET
    
partes_eliminar:
    path:     /{id}/eliminarParte
    defaults: { _controller: "PartesBundle:Partes:delete" }
    methods:  GET
#
#partes_busca:
#    path:     /buscaParte
#    defaults: { _controller: "PartesBundle:Partes:buscaParteNombre" }
#    methods:  [POST]